site_name: Call Changes Simulator Docs
site_url: 'https://dvavasour.gitlab.io/bell3/call-change-sim-docs'
site_dir: 'public'
docs_dir: 'docs'

theme:
  name: material
  navigation_depth: 2

markdown_extensions:
    - toc:
        permalink: '#'
    - admonition
    - attr_list
